version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - APP_ENV=prod
    command: "php-fpm"

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - .docker/nginx/grilli.com.conf:/etc/nginx/conf.d/nginx.conf
      - .:/var/www/html
    depends_on:
      - app
