version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      #Port utilisé par ma machine : Port retenu à l'intérieur du conteneur
    ports:
      - "4173:3000"
    depends_on:
      - server
