version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}"

  nginx : 
    container_name: nginx
    image : nginx:1.25.3-alpine
    volumes : 
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "${NGINX_PORT}"
    depends_on:
      - client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT}"
    depends_on:
      - server
