version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://server:3000
    depends_on:
      - server
